### PR TITLE
added snippets for React component lifecycle methods

### PR DESCRIPTION
**Pull request by williamle8300**
Hi, thanks for putting this bundle together! Just wanna ping you to see if you want some snippets I added.

### CODE REVIEW

**Comment by jjeising** [comment]
Adding more snippets is a good idea and this looks promising.

I'm a little bit reluctant as the tab triggers don't seem very intuitive (e.g. `rnd`) and include large examples but only a few captures (like `{$1}`). If you're interested in working these towards more generally useful triggers I can provide an example and talk more about what I like to see.

Otherwise it may be better to keep them in a fork – they probably provide good guidance for beginners.

**Comment by williamle8300** [comment]
I'm a bit of a n00b with TextMate snippets. These is the first one I've made so I'm not really sure what you mean by making it better. Can you give me some direction?

**Comment by williamle8300** [comment]
I think they're pretty cool, and convenient. I added comments with some of the least-used lifecycle methods to remind people what their purposes are for. I dunno... give me some direction!

**Comment by jjeising** [comment]
The proposed triggers currently work more like documentation than useful shortcuts (imagine deleting content from `propType` everytime). Their usefulness may also be greatly reduce in the currently evolving flux environments.

I may pull `render` as an example for a useful trigger, but then I'm not sure how to separate ES 6 class syntax?

I'm going to close this for now.

**Comment by williamle8300** [comment]
Ok no prob. I'm a newbie to react and js so this helped me. I haven't gotten around to using ES6 yet. My attitude is that if you need a transport then it's not a real language (much like coffeescript). That's just my approach which I don't think is really fashionable but i think it makes sense.

**Pull request closed without merging**
